# Generated by Django 5.0.4 on 2024-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('occupied', 'Besetzt')], default='available', max_length=10)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
