# Generated by Django 5.0.4 on 2024-05-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservierung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=15)),
                ('datum', models.DateField()),
                ('uhrzeit', models.TimeField()),
                ('gaeste', models.IntegerField()),
                ('besondere_wuensche', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('sitzplaetze', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TableManagement.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='reservierung',
            name='tisch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TableManagement.tisch'),
        ),
    ]
