# Generated by Django 5.0.4 on 2024-05-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0002_reservierung_restaurant_tisch_delete_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('special_requests', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tisch',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Reservierung',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Tisch',
        ),
    ]
