# Generated by Django 5.0.4 on 2024-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Totaltable_number', models.IntegerField()),
                ('onetofortable', models.IntegerField()),
                ('fortoeisixtable', models.IntegerField()),
                ('sixtoeighttable', models.IntegerField()),
                ('morthaneight', models.IntegerField()),
            ],
        ),
    ]
