# Generated by Django 5.0.4 on 2024-06-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestaurantManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Totaltable_number', models.IntegerField()),
                ('onetofortable', models.IntegerField()),
                ('fortoeisixtable', models.IntegerField()),
                ('sixtoeighttable', models.IntegerField()),
                ('morthaneight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('count', models.IntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationManagement.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagement.restaurant')),
            ],
        ),
    ]
