# Generated by Django 5.0.4 on 2024-06-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0002_alter_reservation_user'),
        ('RestaurantManagement', '0001_initial'),
        ('TableManagement', '0002_remove_table_restaurant_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('count', models.IntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationManagement.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagement.restaurant')),
            ],
        ),
    ]
