# Generated by Django 5.0.4 on 2024-05-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0003_table_remove_tisch_restaurant_delete_reservierung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='special_requests',
            field=models.TextField(),
        ),
    ]
