# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0004_table_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='count',
        ),
    ]
