# Generated by Django 5.0.4 on 2024-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0004_alter_table_special_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restourant', models.CharField(max_length=100)),
                ('Kudne', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('Tablenummer', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='Restourant',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='guests',
            new_name='Tablenummer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='table',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
    ]
