# Generated by Django 5.0.4 on 2024-05-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0005_kunde_rename_name_table_restourant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kunde',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
